### ISSUE TITLE
`is null` and `is not null` can't be used in expression contexts

### ISSUE THREAD

**Issue by jnm2** [AArnott/CSharpIsNull#3]
Looking at https://github.com/AArnott/CSharpIsNull/blob/main/src/CSharpIsNullAnalyzer/CSIsNull001.cs and https://github.com/AArnott/CSharpIsNull/blob/main/src/CSharpIsNullAnalyzer/CSIsNull002.cs, I didn't see anything checking for this.

```cs
using System;
using System.Linq.Expressions;

// ❌ CS8122 An expression tree may not contain an 'is' pattern-matching operator.
//                                        ↓↓↓↓↓↓↓↓↓
_ = (Expression<Func<string, bool>>)(s => s is null);

// ❌ CS8122 An expression tree may not contain an 'is' pattern-matching operator.
//                                        ↓↓↓↓↓↓↓↓↓↓↓↓↓
_ = (Expression<Func<string, bool>>)(s => s is not null);

_ = (Expression<Func<string, bool>>)(s => s is object); // Works
```

[(SharpLab)](https://sharplab.io/#v2:EYLgtghglgdgNAFxANwKYCcoDMCeAfAAQCYBGAWACgCAGAAgJIDoAZWAR0YFEAPAB3VQBnQVAD2MQQG5KlAPSzagGXJaAYQDKADhJEitAIIxaqPgOFjDCAalqQctGKIS0AxuITRDEQwHIog77S8EAgIGDAAtJAIzgAWsADmtKK8GMGi6IxyCrQ5uXn5BYVFuYDJhGXl5ZQA+rQAvLQAFDz8QiLiADwEAKydJNRwtMCiogA2AHxjAJQNgnVjtLN+9gCuIyOT0hRZSqqa2roGRiat5rSWqNa29o4ubh60XrS+/oHBoegRUbEJSSnoaRltsVgSDihVwRVqnVGs1TG0YJ0egx+oNhuMpjM5gtaEsHE4YKt1psofUmsczB1ur0UUNRhNprNavNFrNRMAAFaoZwIDa0eS0ADq6QA1oJKEA)

**Comment by jnm2** [comment]
This is what I settled on to deal with recursive nesting properly: https://github.com/dotnet/roslyn/discussions/51446#discussioncomment-427746

**Comment by AArnott** [comment]
Interesting. Do you have time to send a PR with tests and a fix?

**Comment by jnm2** [comment]
Sorry, probably not soon.
