### ISSUE TITLE
Wrong codefix for '== default'

### ISSUE THREAD

**Issue by manfred-brands** [AArnott/CSharpIsNull#41]
When I enabled this analyzer it correctly complained about `checkedTypes == default`,
But the code fix doesn't result in `checkedType is null` as expected but in `default is null`:

![image](https://user-images.githubusercontent.com/8655218/235396297-94896128-e958-4b5c-a5ba-a11589b3805f.png)

This is because the code tries to handle `null == checkedTypes` and only tests if the right hand is `null`:
```csharp
expr.Right is LiteralExpressionSyntax { RawKind: (int)SyntaxKind.NullLiteralExpression }
```

**Comment by AArnott** [comment]
Thank you for your report and analysis. Would you be interested in submitting a PR?

**Comment by manfred-brands** [comment]
Done.
